site_name: vmcnet
repo_url: https://github.com/jeffminlin/vmcnet
repo_name: jeffminlin/vmcnet
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: default
      primary: deep-purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep-purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking

plugins:
  - search
  - mkdocstrings:
      watch:
        - vmcnet
      handlers:
        python:
          selection:
            inherited_members: False
          rendering:
            heading_level: 3
            members_order: source
            show_root_heading: False
            show_root_full_path: False
            show_object_full_path: False
            show_category_heading: False
  - mike
  - gen-files:
      scripts:
        - docs/gen_api_ref.py
  - literate-nav:
      nav_file: api_nav.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - API Reference: api/
  - Contributing: CONTRIBUTING.md

extra:
  version:
    provider: mike

extra_css:
  - stylesheets/docstrings.css
  - stylesheets/sidebar.css
  - stylesheets/content.css
